name: Docker Image

on:
  push:

permissions:
  contents: read

jobs:
  verify:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/_docker_image.yml
    with:
      context: docker
      file: docker/Containerfile
      image: ${{ vars.DOCKER_USERNAME }}/jetify-devbox
      docker-username: ${{ vars.DOCKER_USERNAME }}
      version-file: .devbox-version
      version-build-arg: DEVBOX_VERSION
      push: false

  publish:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_docker_image.yml
    with:
      context: docker
      file: docker/Containerfile
      image: ${{ vars.DOCKER_USERNAME }}/jetify-devbox
      docker-username: ${{ vars.DOCKER_USERNAME }}
      version-file: .devbox-version
      version-build-arg: DEVBOX_VERSION
      push: true
    secrets:
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
